# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c120a63bab0038509ed358a62b74fcea8c3ac51c0e20bd0932e68d6121fdf5aeea48942cade33a817bb5fd2fdf7a0bbdf45cae4db33a489b3bada686a2c86cf3

test:
  secret_key_base: f4034e0ed4b497cfb2058b7399f3eba6573c74bcf12fd1b03f9bbaec65324a8d3223c835478df49a0b61564ca70794f04993474afac4d8cb944b04ace29d8e1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
